### ISSUE TITLE
Navigation type

### ISSUE THREAD

**Issue by Micheemukeba** [Step-Labs-Sf/flow-button-doc#2]
Hi, I added the Nav button to my screen flow with 3 screens . theres fields that are required in screen 2 . when i use the close button in screen 2, it does not close the screen flow as expected. the navigation types are BACK, NEXT, PAUSE and FINISH. I used the Finish nav type and nothing happens when i click the button, the next & back button would be met with validation error on the required field. How can i resolve this

**Comment by Damecek** [comment]
FINISH is only available for the last screen element in your flow, in this case it is instead of the NEXT. If you want to branch the next screen you need to have a decision element based on the button clicked. 
For more information please see the wiki section.
