### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Volodymyr-Meda** [Step-Labs-Sf/flow-button-doc#3]
We are currently encountering an issue while attempting to install the package to production. You can see the error on the attached screenshot

<img width="1036" alt="error" src="https://github.com/user-attachments/assets/f7718f80-1c06-4d7f-a0cf-539e81656c7d">

**Comment by rapphasilva** [comment]
@Damecek Facing the same problem here...
@Volodymyr-Meda Did you already know how to solve?

**Comment by Damecek** [comment]
Hello there,

unfortunately the packaging org have been deactivated by Salesforce and with it all package versions. Therefore it is not possible to install the package from AppExchange. 

You can try out the new standard Flow Button component https://help.salesforce.com/s/articleView?id=sf.fsc_flow_ref_elements_screencmp_screenbutton.htm&type=5. 

Regards
Adam

**Comment by Damecek** [comment]
here is [repo](https://github.com/Step-Labs-Sf/flow-button) containing the source code of the package
